### ISSUE TITLE
Table plagiarism_vericite_score is not created

### ISSUE THREAD

**Issue by NorthernMichU** [LongsightGroup/moodle-plagiarism_vericite#11]
I noticed when I installed the plugin that the plagiarism_vericite_score table was not created.  Looking at db/install.xml the closing tables tag happens before the plagiarism_vericite_score table is created.  Moving that closing tables tag below the code for the plagiarism_vericite_score table fixes the issue and the table is created.

**Comment by baholladay** [comment]
Thanks, I've fixed this. One of the pitfalls of not testing the install script every upgrade.
