### ISSUE TITLE
plagiarism_plugin::cron() will be deprecated in Moodle 3.1

### ISSUE THREAD

**Issue by danmarsden** [LongsightGroup/moodle-plagiarism_vericite#30]
FYI - In Moodle 3.1 (not yet released) plagiarism plugins that call the plagiarism_plugin::cron() function will throw a debugging warning stating that the cron function is now deprecated - plugins should move to using the newer "scheduled tasks" process instead. Eventually the function will be removed from a future Moodle release which may prevent your plugin from working unless you have converted to using scheduled tasks.

More information on this change is available in https://tracker.moodle.org/browse/MDL-52702

Developer documentation on scheduled tasks is available here:
https://docs.moodle.org/dev/Task_API

an example of a plagiarism plugin that has converted to the new scheduled tasks is the URKUND plugin - feel free to copy/borrow/re-use the code here:
https://github.com/danmarsden/moodle-plagiarism_urkund/blob/master/db/tasks.php
https://github.com/danmarsden/moodle-plagiarism_urkund/tree/master/classes/task

**Comment by baholladay** [comment]
Thanks for the information! We'll get this updated soon. What is the Moodle compatibility range for scheduled tasks (i.e. Moodle 2.7+, $plugin->requires=XXXX)?

**Comment by baholladay** [comment]
I've set it to 2.7.0: $plugin->requires = 2014051200;

Let me know if this isn't correct

**Comment by danmarsden** [comment]
yeah - 2.7 is right afaik. It's a pain that we still have to maintain an empty "cron()" function in 2.7->3.0 but we will be able to remove it completely from the plugins in 3.1

**Comment by baholladay** [comment]
Thanks!
