### ISSUE TITLE
Warning after installation on MDL 3.1

### ISSUE THREAD

**Issue by shatami** [LongsightGroup/moodle-plagiarism_vericite#36]
Installed Vericite on Moodle 3.1.2 and the site has following errors:

```
Warning: include(/var/www/data/default/public_html/plagiarism/vericite/version.php): failed to open stream: No such file or directory in /var/www/data/default/public_html/lib/classes/plugin_manager.php on line 318

Warning: include(): Failed opening '/var/www/data/default/public_html/plagiarism/vericite/version.php' for inclusion (include_path='/var/www/data/default/public_html/lib/pear:.:/usr/share/pear:/usr/share/php') in /var/www/data/default/public_html/lib/classes/plugin_manager.php on line 318
Plugin plagiarism_vericite does not declare valid $plugin->component in its version.php.
line 328 of /lib/classes/plugin_manager.php: call to debugging()
line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
line 43 of /admin/settings/plugins.php: call to core_plugin_manager->get_plugins_of_type()
line 7279 of /lib/adminlib.php: call to require()
line 7164 of /lib/adminlib.php: call to admin_get_root()
line 203 of /admin/plugins.php: call to admin_externalpage_setup()
```

**Comment by baholladay** [comment]
What version of VeriCite did you install? Also, did you follow the instructions on http://help.vericite.com/m/integrations/l/470561-moodle-integration-instructions

I haven't seen this error before and the warning message makes me believe you may have not installed it as a plagiarism plugin under "plugins->plagiarism" or that you may not have admin access.

**Comment by shatami** [comment]
I installed the latest version. The issue is the zip file I download from https://moodle.org/plugins/pluginversions.php?plugin=plagiarism_vericite, has a nested folder structure and a __MACOSX file within it. Please see screenshot.
![vericite](https://cloud.githubusercontent.com/assets/23088147/19785561/acbec33a-9c4e-11e6-8ed0-085ba87265e3.png)

**Comment by baholladay** [comment]
Thanks... Uploading the zip to Moodle's plugins directory was supposed to automatically remove system folders like that. We will look into why it wasn't removed. Does it work fine for you if you remove that folder and re-zip?

**Comment by shatami** [comment]
Yes, the plugin itself is working.

**Comment by shatami** [comment]
Can you fix the packaging problem, we need it to be in the correct folder structure after downloading from Moodle plugin page.

**Comment by baholladay** [comment]
I have updated the plugin zip, please try it again
