### ISSUE TITLE
Issue in .zip distribution on Moodle.org

### ISSUE THREAD

**Issue by gnat** [LongsightGroup/moodle-plagiarism_vericite#42]
The "__MACOSX" folder in the .zip file distribution breaks automated installation of this package (example: composer). Please remove this folder, thanks!

Issue present in both current versions:
2017021600
2015120201

No issue in:
2016082900

The Zip distribution in question is found at: https://moodle.org/plugins/pluginversions.php?plugin=plagiarism_vericite Posting here to get the attention of @ottenhoff @baholladay.

**Comment by baholladay** [comment]
Thanks! This should be fixed now.

**Comment by gnat** [comment]
Thanks! @baholladay
