### ISSUE TITLE
Undefined index: vericite_preliminary_report when submitting a new file

### ISSUE THREAD

**Issue by hernan43** [LongsightGroup/moodle-plagiarism_vericite#46]
I recently installed version 2017060100 on one of my Moodle sites. When I make a submission we get the following debug warning/error:

> PHP Notice:  Undefined index: vericite_preliminary_report in /var/www/engage/releases/20170602154319/learn/plagiarism/vericite/lib.php on line 196

Looking at line 196 in lib.php:

https://github.com/vericite/moodle-plagiarism_vericite/blob/master/lib.php#L196

I see:

`$viewPreliminaryReport = $plagiarismsettings['vericite_preliminary_report'];`

I'm not sure if this is an issue with my config or not but I'm wondering if it wouldn't be better to have that line look something like:

`$viewPreliminaryReport = isset($plagiarismsettings['vericite_preliminary_report']) ? $plagiarismsettings['vericite_preliminary_report'] : false;`

I think it is just a warning so it isn't breaking anything as far as I can tell. I just thought it might be cleaner to at least force a default value in the event the config is missing.

**Comment by baholladay** [comment]
Thanks! We'll look into this and update it. Just quickly looking at your code, it sounds like a good solution.
