### ISSUE TITLE
Installation Fails on 2.6.x and 2.7.x

### ISSUE THREAD

**Issue by NorthernMichU** [LongsightGroup/moodle-plagiarism_vericite#8]
When I try to install this on either 2.6 or 2.7 I get an XMLDB error.  Looking into isntall.xml I found that changing the type on the field data (in table plagiarism_vericite_files) to text (from longtext) fixes the issue and (on mysql anyway) keeps the desired datatype of longtext.

**Comment by baholladay** [comment]
Thanks for the heads up! I've fixed this and released a new version. This version also makes a change in inline submissions default behavior, so I would suggest upgrading as soon as you can.
